//! Built-in source catalog shared by database initialization and collectors.

/// Immutable metadata for one public topic source.
#[derive(Debug, Clone, Copy)]
pub struct PlatformDefinition {
    pub code: &'static str,
    pub display_name: &'static str,
    pub home_url: &'static str,
    pub endpoint_url: &'static str,
}

/// Product catalog. Feed URLs remain local database fields so a later settings UI can override them.
pub const PLATFORM_CATALOG: &[PlatformDefinition] = &[
    PlatformDefinition { code: "qbitai", display_name: "量子位", home_url: "https://www.qbitai.com/", endpoint_url: "https://www.qbitai.com/feed" },
    PlatformDefinition { code: "ithome", display_name: "IT之家", home_url: "https://www.ithome.com/", endpoint_url: "https://www.ithome.com/rss/" },
    PlatformDefinition { code: "36kr", display_name: "36氪", home_url: "https://36kr.com/", endpoint_url: "https://36kr.com/hot-list/catalog" },
    PlatformDefinition { code: "huxiu", display_name: "虎嗅", home_url: "https://www.huxiu.com/", endpoint_url: "https://www.huxiu.com/" },
    PlatformDefinition { code: "c114", display_name: "C114通信", home_url: "https://www.c114.com.cn/", endpoint_url: "https://www.c114.com.cn/" },
    PlatformDefinition { code: "wallstreetcn", display_name: "华尔街见闻", home_url: "https://wallstreetcn.com/", endpoint_url: "https://wallstreetcn.com/" },
    PlatformDefinition { code: "odaily", display_name: "Odaily星球日报", home_url: "https://www.odaily.news/", endpoint_url: "https://www.odaily.news/" },
    PlatformDefinition { code: "xueqiu", display_name: "雪球", home_url: "https://xueqiu.com/", endpoint_url: "https://xueqiu.com/today" },
    PlatformDefinition { code: "toutiao", display_name: "今日头条", home_url: "https://www.toutiao.com/", endpoint_url: "https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc" },
    PlatformDefinition { code: "thepaper", display_name: "澎湃新闻", home_url: "https://www.thepaper.cn/", endpoint_url: "https://www.thepaper.cn/" },
    PlatformDefinition { code: "zhihu", display_name: "知乎", home_url: "https://www.zhihu.com/", endpoint_url: "https://www.zhihu.com/api/v3/feed/topstory/hot-lists/total?limit=100&desktop=true" },
    PlatformDefinition { code: "binance-square-zh", display_name: "币安广场中文", home_url: "https://www.binance.com/zh-CN/square", endpoint_url: "https://www.binance.com/bapi/composite/v3/friendly/pgc/content/article/list?pageIndex=1&pageSize=20&type=1" },
    PlatformDefinition { code: "binance-square-global", display_name: "币安广场全球", home_url: "https://www.binance.com/en/square", endpoint_url: "https://www.binance.com/bapi/composite/v3/friendly/pgc/content/article/list?pageIndex=1&pageSize=20&type=1" },
    PlatformDefinition { code: "hacker-news", display_name: "Hacker News", home_url: "https://news.ycombinator.com/", endpoint_url: "https://hacker-news.firebaseio.com/v0" },
    PlatformDefinition { code: "wikipedia-zh", display_name: "Wikipedia 中文", home_url: "https://zh.wikipedia.org/", endpoint_url: "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/zh.wikipedia/all-access" },
    PlatformDefinition { code: "wikipedia-global", display_name: "Wikipedia 全球", home_url: "https://en.wikipedia.org/", endpoint_url: "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/en.wikipedia/all-access" },
    PlatformDefinition { code: "mastodon-zh", display_name: "Mastodon 中文", home_url: "https://m.cmx.im/", endpoint_url: "https://m.cmx.im/api/v1/trends/statuses?limit=40" },
    PlatformDefinition { code: "mastodon-global", display_name: "Mastodon 全球", home_url: "https://mastodon.social/", endpoint_url: "https://mastodon.social/api/v1/trends/links?limit=40" },
    PlatformDefinition { code: "google-trends-zh", display_name: "Google Trends 中文", home_url: "https://trends.google.com/trending?geo=TW", endpoint_url: "https://trends.google.com/trending/rss?geo=TW" },
    PlatformDefinition { code: "google-trends-global", display_name: "Google Trends 全球", home_url: "https://trends.google.com/trending?geo=US", endpoint_url: "https://trends.google.com/trending/rss?geo=US" },
    PlatformDefinition { code: "coingecko", display_name: "CoinGecko", home_url: "https://www.coingecko.com/", endpoint_url: "https://api.coingecko.com/api/v3/search/trending" },
    PlatformDefinition { code: "github", display_name: "GitHub", home_url: "https://github.com/trending", endpoint_url: "https://github.com/trending?since=daily" },
    PlatformDefinition { code: "hugging-face", display_name: "Hugging Face", home_url: "https://huggingface.co/papers", endpoint_url: "https://huggingface.co/api/daily_papers" },
    PlatformDefinition { code: "arxiv", display_name: "arXiv", home_url: "https://arxiv.org/", endpoint_url: "https://arxiv.org/list/cs.AI/recent?skip=0&show=100" },
    PlatformDefinition { code: "bluesky", display_name: "Bluesky", home_url: "https://bsky.app/", endpoint_url: "https://public.api.bsky.app/xrpc/app.bsky.unspecced.getTrendingTopics" },
    PlatformDefinition { code: "polymarket", display_name: "Polymarket", home_url: "https://polymarket.com/", endpoint_url: "https://gamma-api.polymarket.com/markets?active=true&closed=false&order=volume24hr&ascending=false&limit=100" },
    PlatformDefinition { code: "stack-overflow", display_name: "Stack Overflow", home_url: "https://stackoverflow.com/", endpoint_url: "https://api.stackexchange.com/2.3/questions?site=stackoverflow&sort=hot&pagesize=100&filter=default" },
    PlatformDefinition { code: "dev-community", display_name: "DEV Community", home_url: "https://dev.to/", endpoint_url: "https://dev.to/api/articles?top=1&per_page=100" },
    PlatformDefinition { code: "lobsters", display_name: "Lobsters", home_url: "https://lobste.rs/", endpoint_url: "https://lobste.rs/rss" },
    PlatformDefinition { code: "techcrunch", display_name: "TechCrunch", home_url: "https://techcrunch.com/", endpoint_url: "https://techcrunch.com/feed/" },
    PlatformDefinition { code: "federal-reserve", display_name: "美联储", home_url: "https://www.federalreserve.gov/", endpoint_url: "https://www.federalreserve.gov/feeds/press_all.xml" },
    PlatformDefinition { code: "sec", display_name: "美国 SEC", home_url: "https://www.sec.gov/", endpoint_url: "https://www.sec.gov/news/pressreleases.rss" },
    PlatformDefinition { code: "bbc-chinese", display_name: "BBC 中文", home_url: "https://www.bbc.com/zhongwen/simp", endpoint_url: "https://feeds.bbci.co.uk/zhongwen/simp/rss.xml" },
    PlatformDefinition { code: "dw-chinese", display_name: "德国之声中文", home_url: "https://www.dw.com/zh/", endpoint_url: "https://rss.dw.com/rdf/rss-chi-all" },
    PlatformDefinition { code: "rfi-chinese", display_name: "法广中文", home_url: "https://www.rfi.fr/cn/", endpoint_url: "https://www.rfi.fr/cn/rss" },
    PlatformDefinition { code: "bloomberg", display_name: "彭博社", home_url: "https://www.bloomberg.com/", endpoint_url: "https://feeds.bloomberg.com/markets/news.rss" },
    PlatformDefinition { code: "jin10", display_name: "金十数据", home_url: "https://www.jin10.com/", endpoint_url: "https://flash-api.jin10.com/get_flash_list?channel=-8200&vip=1" },
    PlatformDefinition { code: "cls", display_name: "财联社", home_url: "https://www.cls.cn/", endpoint_url: "https://news.orz.ai/api/v1/dailynews/?platform=cls" },
    PlatformDefinition { code: "xiaohongshu", display_name: "小红书", home_url: "https://www.xiaohongshu.com/", endpoint_url: "https://www.xiaohongshu.com/explore" },
    PlatformDefinition { code: "weibo", display_name: "新浪微博", home_url: "https://weibo.com/", endpoint_url: "https://news.orz.ai/api/v1/dailynews/?platform=weibo" },
    PlatformDefinition { code: "douyin", display_name: "抖音", home_url: "https://www.douyin.com/", endpoint_url: "https://news.orz.ai/api/v1/dailynews/?platform=douyin" },
    PlatformDefinition { code: "bilibili", display_name: "B站", home_url: "https://www.bilibili.com/", endpoint_url: "https://news.orz.ai/api/v1/dailynews/?platform=bilibili" },
    PlatformDefinition { code: "baidu", display_name: "百度", home_url: "https://top.baidu.com/", endpoint_url: "https://news.orz.ai/api/v1/dailynews/?platform=baidu" },
    PlatformDefinition { code: "the-verge", display_name: "The Verge", home_url: "https://www.theverge.com/", endpoint_url: "https://www.theverge.com/rss/index.xml" },
    PlatformDefinition { code: "ars-technica", display_name: "Ars Technica", home_url: "https://arstechnica.com/", endpoint_url: "https://feeds.arstechnica.com/arstechnica/index" },
    PlatformDefinition { code: "mit-technology-review", display_name: "MIT Technology Review", home_url: "https://www.technologyreview.com/", endpoint_url: "https://www.technologyreview.com/feed/" },
    PlatformDefinition { code: "infoq", display_name: "InfoQ", home_url: "https://www.infoq.com/", endpoint_url: "https://feed.infoq.com/" },
    PlatformDefinition { code: "sspai", display_name: "少数派", home_url: "https://sspai.com/", endpoint_url: "https://sspai.com/feed" },
    PlatformDefinition { code: "solidot", display_name: "Solidot", home_url: "https://www.solidot.org/", endpoint_url: "https://rss.solidot.org/index.rss" },
];
